primary:
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.0.210"
  persistence:
    enabled: true
    storageClass: postgres-hostpath-expandable
    size: 15Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m