primary:
  persistence:
    enabled: true
    storageClass: postgres-hostpath-expandable
    size: 15Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m